export enum APPLICATION_STATUS {
  PENDING_FOR_COMAKER_APPROVAL = 'PENDING_FOR_COMAKER_APPROVAL',
  COMAKER_REJECTED             = 'COMAKER_REJECTED',
  FOR_HR_VERIFICATION          = 'FOR_HR_VERIFICATION',
  FOR_HR_ENDORSEMENT           = 'FOR_HR_ENDORSEMENT',
  NEW                          = 'NEW',
  FOR_BI                       = 'FOR_BI',
  FOR_BI_REVIEW                = 'FOR_BI_REVIEW',
  FOR_CI                       = 'FOR_CI',
  FOR_CI_REVIEW                = 'FOR_CI_REVIEW',
  FOR_EVALUATION               = 'FOR_EVALUATION',
  FOR_APPROVAL                 = 'FOR_APPROVAL',
  HR_REJECTED                  = 'HR_REJECTED',
  APPROVED                     = 'APPROVED',
  ACCEPTED                     = 'ACCEPTED',
  DOCUMENTED                   = 'DOCUMENTED',
  BOOKED                       = 'BOOKED',
  DISBURSED                    = 'DISBURSED',
  DECLINED                     = 'DECLINED',
  AMENDMENT                    = 'AMENDMENT',
  RECONSIDER                   = 'RECONSIDER',
  CLOSED                       = 'CLOSED',

}

export enum APPLICATION_STATUS_LABEL {
  PENDING_FOR_COMAKER_APPROVAL = 'Pending for Co-Maker Approval',
  FOR_HR_VERIFICATION          = 'For HR Verification',
  FOR_HR_ENDORSEMENT           = 'Verified (For HR Endorsement)',
  IN_PROCESS                   = 'In Process',
  HR_REJECTED                  = 'HR-Rejected',
  APPROVED                     = 'APPROVED',
  BOOKED                       = 'BOOKED',
  CLOSED                       = 'CLOSED',
}

export const LIST_APPLICATION_STATUS = [
  { value: 'PENDING_FOR_COMAKER_APPROVAL', internalLabel: 'For Comaker Approval', externalLabel: 'Pending for Co-Maker' },
  { value: 'COMAKER_REJECTED', internalLabel: 'Comaker Rejected', externalLabel: 'Comaker rejected' },
  { value: 'FOR_HR_VERIFICATION', internalLabel: 'For HR Verification', externalLabel: 'Pending for HR Verification' },
  { value: 'FOR_HR_ENDORSEMENT', internalLabel: 'For HR Endorsement', externalLabel: 'Pending for HR Endorsement' },
  { value: 'NEW', internalLabel: 'New', externalLabel: 'In Processs' },
  { value: 'FOR_BI', internalLabel: 'For BI', externalLabel: 'In Processs' },
  { value: 'FOR_BI_REVIEW', internalLabel: 'For BI Review', externalLabel: 'In Processs' },
  { value: 'FOR_CI', internalLabel: 'For CI', externalLabel: 'In Processs' },
  { value: 'FOR_CI_REVIEW', internalLabel: 'For CI Review', externalLabel: 'In Processs' },
  { value: 'FOR_EVALUATION', internalLabel: 'For Evaluation', externalLabel: 'In Processs' },
  { value: 'FOR_APPROVAL', internalLabel: 'For Approval', externalLabel: 'In Processs' },
  { value: 'HR_REJECTED', internalLabel: 'HR Rejected', externalLabel: 'Rejected by HR' },
  { value: 'APPROVED', internalLabel: 'Approved', externalLabel: 'Approved' },
  { value: 'ACCEPTED', internalLabel: 'Accepted', externalLabel: 'Approved' },
  { value: 'DOCUMENTED', internalLabel: 'Documented', externalLabel: 'Approved' },
  { value: 'BOOKED', internalLabel: 'Booked', externalLabel: 'Approved' },
  { value: 'DISBURSED', internalLabel: 'Disbursed', externalLabel: 'Loan Disbursed' },
  { value: 'DECLINED', internalLabel: 'Declined', externalLabel: 'Declined' },
  { value: 'AMENDMENT', internalLabel: 'Amendment', externalLabel: 'In Process' },
  { value: 'RECONSIDER', internalLabel: 'Reconsider', externalLabel: 'In Process' },
  { value: 'CLOSED', internalLabel: 'Closed', externalLabel: 'Closed' },
];

export const LIST_EXTERNAL_APPLICATION_STATUS = [
  { values: ['PENDING_FOR_COMAKER_APPROVAL'], externalLabel: 'Pending for Co-Maker' },
  { values: ['COMAKER_REJECTED'], externalLabel: 'Comaker rejected' },
  { values: ['FOR_HR_VERIFICATION'], externalLabel: 'Pending for HR Verification' },
  { values: ['FOR_HR_ENDORSEMENT'], externalLabel: 'Pending for HR Endorsement' },
  { values: ['HR_REJECTED'], externalLabel: 'Rejected by HR' },
  { values: ['NEW', 'FOR_BI', 'FOR_BI_REVIEW', 'FOR_CI', 'FOR_CI_REVIEW', 'FOR_EVALUATION', 'FOR_APPROVAL', 'AMENDMENT', 'RECONSIDER'], externalLabel: 'In Process' },
  { values: ['APPROVED', 'ACCEPTED', 'DOCUMENTED', 'BOOKED'], externalLabel: 'Approved' },
  { values: ['DISBURSED'], externalLabel: 'Loan Disbursed' },
  { values: ['DECLINED'], externalLabel: 'Declined' },
  { values: ['CLOSED'], externalLabel: 'Closed' },
];
