version: '2'

services:
  db:
    container_name: dgte-erp-games-db
    image: kaitengame/postgres:1.0
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: 'dgte_erp_games'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  games:
    container_name: dgte-erp-games
    image: kaitengame/dgte-erp-games:0.0.1-SNAPSHOT
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
      JVM_OPTS: '-Xmx128m -Xms128m -XX:MaxPermSize=64m'
    volumes:
      - /var/log/games:/var/log/games
  ui:
    container_name: dgte-erp-games-ui
    image: kaitengame/dgte-erp-games-ui:1.0
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:80'
    environment:
      WAIT_HOSTS: games:8083
volumes:
  postgres-data: