server:
  port: 8089

logging:
  level:
    com.dgte: DEBUG

firebase:
  config-file: dgte-erp-rent-firebase-adminsdk.json
  service-account-filename: dgte-erp-rent-firebase-adminsdk.json
  realtime-database-url: https://dgte-erp-rent.firebaseio.com
